### ISSUE TITLE
What hardware do you use? does it need a special license key?

### ISSUE THREAD

**Issue by almostnobody** [t184256/gaze-streamer#1]
@t184256  sorry to bother you, i just saw tobii 4c available to purchase, and I am wondering if it is possible to make it work on linux?
In some places on the internet tobii company says i will need to buy some special upgrade pro key for their research license.
Did you?

**Comment by t184256** [comment]
Tobii 4C with the drivers taken from https://github.com/MoscowskyAnton/tobii_eye_tracker_linux_installer and repackaged for NixOS. Basic gaze tracking requires no special licenses; more advanced things like, e.g. per-eye data or backlight control do.

**Comment by almostnobody** [comment]
great, thanks for the quick answer
will order it now, and will be using it with NixOS as well

**Comment by almostnobody** [comment]
i can see you use gnome desktop, how is it with the eye tracking? do you use eyetracking in day to day pc interaction?

**Comment by t184256** [comment]
0 (zero) integration whatsoever.

When I used it for clicking purposes, I had a script that worked with sway but is unlikely to work under gnome.

Basically, you'll only have two coordinates to work with, the rest is up to you.

**Comment by almostnobody** [comment]
got it, so you don't use it right now?
Why? was it that bad?

**Comment by almostnobody** [comment]
is that script public? i would appreciate if you open sourced it, i'm thinking to switch to wayfire(wlroots based)

**Comment by t184256** [comment]
I don't use it as a mouse replacement or even a supplement. No matter what compensation and dynamic calibration schemes I came up with, the precision was only enough to reliably hit ~2cm-sized targets, and my dream was to reliably jump around VIM in a 80x25 terminal on 27". I've tried installing several trackers at once to increase the covered area and precision, but turns out their backlight pulses have to be synchronized or disabled, and that stuff needs a license. My health got better and I gave up.

re. script: might be need extra work to open-source. Not public, I'll look for it though. It's basically "receive the stream from gaze-streamer, wait for keypresses. on press, pop up an icon. user's gaze darts towards it, you know how off you were, save this dynamic correction data. on release, click". Drawing at a custom location portably is harder than everything else.
